---
title: "Galactic Empire"
author: "Cédric BAZILE"
format: html
editor: visual
---

<center>

## Github Link : 

<https://github.com/CBZ1310/galactic_empire>

</center>

<br>

## Setup

```{r}
here::i_am("galactic_empire.Rproj")
library(here)
library(ggplot2)
library(dplyr)
library(tidyr)
library(labelled)
library(readr)
```

## Question 3

```{r Importation_of_the_main_dataset}
planets <- read_delim("Main_Dataset/planets.csv")
names(planets) #I check again the name of each column
planets_t <- planets %>% as_tibble()
```

```{r Checking_the_number_of_Planets}
test <- (planets %>% unique() %>% nrow())
answer_to_test <- print(test == 988)
```

At the question, is there 988 rows (and therefore planet), the answer of our test is `r answer_to_test`. We have indeed `r test` rows on the expected 988.

```{r Checking_if_all_the_numeric_values_are_recognized}
c_names <- planets_t %>%  
  select(where(is.numeric))%>%
  names()  

c_names %>%   
  knitr::kable(caption = "List of numeric variable", format = "markdown", align = 'c') 
```

By looking, the list of our data we observe that the "Radius" column was not recognized as a numeric value.

```{r Transformation_of_the_radius_column}
planets_t <- planets_t %>%
  mutate(Radius = as.numeric(Radius))

c_names_2 <- planets_t %>%  
  select(where(is.numeric))%>%
  names()  

c_names_2 %>%   
  knitr::kable(caption = "List of numeric variable", format = "markdown", align = 'c') 
```

<br>

## Question 4

```{r}
planets_t %>% 
  summarize("N_observ" = n(), "N_col"=ncol(.)) %>% 
  knitr::kable(caption = "Format of the dataset", format = "markdown", align = 'c') 


```

```{r}
 planets_t %>%
  summarize(N_observ = n(), N_col = sum(!grepl("^$", colnames(.))))%>% 
  knitr::kable(caption = "Format of the dataset", format = "markdown", align = 'c') 

```

```{r Number_of_missing_values_by_variable}
planets_t %>%
  summarise(across(everything(), list("N_NA" = ~sum(is.na(.))))) %>% 
  pivot_longer(everything(), names_to = "Variable", values_to = "count") %>% 
   knitr::kable(caption = "Number of missing values", format = "markdown", align = 'c') 
```

```{r}
sum(rowSums(is.na(planets_t)) > 0) %>%
  knitr::kable(caption = "Number of observations with at least one missing value", format = "markdown", align = 'c') 

```

## Question 5

```{r Grapphical_representation_radius_by_density}
planets_t %>% ggplot(aes(x=`DENSITY (EARTH)`,y=Radius)) + geom_point() +
  labs(title = "Radius by density",x = "Density", y = "Radius") + theme_dark()
```
